// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: set_tc128.proto

package proto_tc128

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Weights struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Shape  []int64   `protobuf:"varint,2,rep,packed,name=Shape,proto3" json:"Shape,omitempty"`
	Values []float64 `protobuf:"fixed64,3,rep,packed,name=Values,proto3" json:"Values,omitempty"`
	States []float64 `protobuf:"fixed64,4,rep,packed,name=States,proto3" json:"States,omitempty"`
}

func (x *Weights) Reset() {
	*x = Weights{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_tc128_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Weights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weights) ProtoMessage() {}

func (x *Weights) ProtoReflect() protoreflect.Message {
	mi := &file_set_tc128_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weights.ProtoReflect.Descriptor instead.
func (*Weights) Descriptor() ([]byte, []int) {
	return file_set_tc128_proto_rawDescGZIP(), []int{0}
}

func (x *Weights) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Weights) GetShape() []int64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *Weights) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Weights) GetStates() []float64 {
	if x != nil {
		return x.States
	}
	return nil
}

type Set struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CostReal      float64    `protobuf:"fixed64,1,opt,name=CostReal,proto3" json:"CostReal,omitempty"`
	CostImaginary float64    `protobuf:"fixed64,2,opt,name=CostImaginary,proto3" json:"CostImaginary,omitempty"`
	Epoch         uint64     `protobuf:"varint,3,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	Weights       []*Weights `protobuf:"bytes,4,rep,name=Weights,proto3" json:"Weights,omitempty"`
}

func (x *Set) Reset() {
	*x = Set{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_tc128_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Set) ProtoMessage() {}

func (x *Set) ProtoReflect() protoreflect.Message {
	mi := &file_set_tc128_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Set.ProtoReflect.Descriptor instead.
func (*Set) Descriptor() ([]byte, []int) {
	return file_set_tc128_proto_rawDescGZIP(), []int{1}
}

func (x *Set) GetCostReal() float64 {
	if x != nil {
		return x.CostReal
	}
	return 0
}

func (x *Set) GetCostImaginary() float64 {
	if x != nil {
		return x.CostImaginary
	}
	return 0
}

func (x *Set) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Set) GetWeights() []*Weights {
	if x != nil {
		return x.Weights
	}
	return nil
}

var File_set_tc128_proto protoreflect.FileDescriptor

var file_set_tc128_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x65, 0x74, 0x5f, 0x74, 0x63, 0x31, 0x32, 0x38, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x74, 0x63, 0x31, 0x32, 0x38, 0x22, 0x63,
	0x0a, 0x07, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x53, 0x68, 0x61, 0x70, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x53, 0x68,
	0x61, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x43,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x43,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x73, 0x74, 0x49,
	0x6d, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d,
	0x43, 0x6f, 0x73, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x45, 0x70,
	0x6f, 0x63, 0x68, 0x12, 0x2e, 0x0a, 0x07, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x74, 0x63, 0x31,
	0x32, 0x38, 0x2e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x07, 0x57, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x74,
	0x63, 0x31, 0x32, 0x38, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_set_tc128_proto_rawDescOnce sync.Once
	file_set_tc128_proto_rawDescData = file_set_tc128_proto_rawDesc
)

func file_set_tc128_proto_rawDescGZIP() []byte {
	file_set_tc128_proto_rawDescOnce.Do(func() {
		file_set_tc128_proto_rawDescData = protoimpl.X.CompressGZIP(file_set_tc128_proto_rawDescData)
	})
	return file_set_tc128_proto_rawDescData
}

var file_set_tc128_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_set_tc128_proto_goTypes = []interface{}{
	(*Weights)(nil), // 0: proto_tc128.Weights
	(*Set)(nil),     // 1: proto_tc128.Set
}
var file_set_tc128_proto_depIdxs = []int32{
	0, // 0: proto_tc128.Set.Weights:type_name -> proto_tc128.Weights
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_set_tc128_proto_init() }
func file_set_tc128_proto_init() {
	if File_set_tc128_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_set_tc128_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Weights); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_tc128_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Set); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_set_tc128_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_set_tc128_proto_goTypes,
		DependencyIndexes: file_set_tc128_proto_depIdxs,
		MessageInfos:      file_set_tc128_proto_msgTypes,
	}.Build()
	File_set_tc128_proto = out.File
	file_set_tc128_proto_rawDesc = nil
	file_set_tc128_proto_goTypes = nil
	file_set_tc128_proto_depIdxs = nil
}
